name: drupal-headless
recipe: drupal10
config:
  webroot: ./drupal/web
  php: '8.3'
  via: apache
  xdebug: true
  drush: 13
  database: mysql
proxy:
  appserver:
    - drupal-headless.lndo.site
  gatsbyjs:
    - gatsbyjs.lndo.site:8000
    - prod.gatsbyjs.lndo.site:9000
services:
  database:
    type: mysql
    creds:
      user: database
      password: database
      database: database
  gatsbyjs:
    type: node:20
    port: 8000
    build:
      - npm i -g gatsby-cli
    overrides:
      environment:
        NPM_CONFIG_PREFIX: /home/node/.npm-global
      volumes:
        - ./gatsbyjs:/app/gatsbyjs
    command:
      - cd /app/gatsbyjs && npm install && npm run develop
tooling:
  npx:
    service: gatsbyjs
    cmd: npx --cwd=/app/gatsbyjs
  npm:
    service: gatsbyjs
    cmd: npm --cwd=/app/gatsbyjs
  yarn:
    service: gatsbyjs
    cmd: yarn --cwd=/app/gatsbyjs
  composer:
    service: appserver
    cmd: composer --working-dir=/app/drupal
  drush:
    service: appserver
    cmd: "/app/drupal/vendor/bin/drush" # Ruta a Drush si está en el proyecto